SP_HELP CLIENTES
CREATE DATABASE CURSO_SQL
/*
CREATE TABLE CLIENTES(

ID                NUMERIC(9)    NOT NULL PRIMARY KEY IDENTITY(1, 1)
,NOME             VARCHAR(60)   NOT NULL
,CPF              CHAR (11)     NOT NULL
,DATA_NASCIMENTO  DATE          NULL
,IDADE            TINYINT       NULL
,DATA_CADASTRO    DATETIME      NOT NULL DEFAULT( GETDATE() )
,ATIVO            BIT           NOT NULL DEFAULT ( 1 )
,LIMITE           NUMERIC(5,2)  NOT NULL DEFAULT(0.00)   

)
*/

INSERT INTO CLIENTES (NOME, CPF, DATA_NASCIMENTO)
VALUES ( 'ITALO MESQUITA VIEIRA', '04438574182', '19/10/1996' )

INSERT INTO CLIENTES (NOME, CPF, DATA_NASCIMENTO, LIMITE)
VALUES ( 'ITALO MESQUITA VIEIRA', '09837462143', '21/10/1998', 100.00 )

INSERT INTO CLIENTES (NOME, CPF, DATA_NASCIMENTO, IDADE, LIMITE)
VALUES ( 'MARIA LETICIA', '19367926573', '21/10/1998', '', 150.00 )

SELECT * FROM CLIENTES

--1 FN:
--TER UMA CHAVE PRIMARIA
--VALORES ATOMICOS (VALOR INDIVISIVEL)
--NAO TER CAMPOS MULTIVALORADOS
